let vowels = ['a', 'e', 'i', 'o', 'u']
console.log(vowels[2])

const fruits = ["apple", 'banana', 'pineapple']
console.log(fruits)
console.log(fruits.shift())
fruits.push("grape", 'melon')
console.log(fruits)
fruits.pop()
console.log(fruits)
fruits.unshift( "kiwi")
console.log(fruits)
const array = vowels.concat(fruits)
console.log(array)
let arr2 = fruits.slice(0, 2)
console.log(arr2)
arr2 = fruits.slice(-4, -2)
console.log(arr2)
fruits.splice(1 , 2, 'orange')
console.log(fruits)
console.log(fruits.indexOf("orange"))